### ISSUE TITLE
Controller crashes by hitting port with a browser (connection without client certificate)

### ISSUE THREAD

**Issue by mrunc** [emptymonkey/revsh#18]
I really didn't think that revsh can't handle this errors and it would simply crash!

peer did not return a certificate on port 443:
`
Controller: Listening on 0.0.0.0:443.
Controller: Connected from xxx.xxx.xxx.xxx:64064.
init_io_control(): SSL_accept(633d90): Success
140491016673024:error:1417C0C7:SSL routines:tls_process_client_certificate:peer did not return a certificate:../ssl/statem/statem_srvr.c:2879:
do_control(): init_io_control(614120): Success
`

unknown ca on random port:
`
Controller: Listening on 0.0.0.0:4433.
Controller: Connected from xxx.xxx.xxx.xxx:64202.
init_io_control(): SSL_accept(633d70): Success
140704924813056:error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:../ssl/record/rec_layer_s3.c:1399:SSL alert number 48
do_control(): init_io_control(614120): Success
`

**Comment by emptymonkey** [comment]
I've changed  failed SSL handshakes to be non-fatal. (The code is very paranoid. Technically it isn't crashing but reports and exits in a very paranoid fashion. This was too paranoid. This should be non-fatal.)  The change is in devel branch. I'll push to master as soon as I get some time to test all the recent changes.

Thanks for the issue!
