### ISSUE TITLE
Error on linux host without libssl

### ISSUE THREAD

**Issue by PowerPress** [emptymonkey/revsh#2]
Please consider if possible only loading a library if a argument is used for it.

./revsh: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

**Comment by emptymonkey** [comment]
I am currently assessing whether or not it is worth the effort to determine which OpenSSL versions are available (if any) on the fly, given how finicky OpenSSL is about version mis-matches. Currently, the "devel" branch has the ability to build without OpenSSL at all. Simply uncomment the appropriate section of the Makefile:

**Comment by emptymonkey** [comment]
I'm going to close this out without a specific patch. I just released a new version where the default profile in the Makefile is to build OpenSSL statically into the binary. Given the nature of this tool, I don't want it ever defaulting to plaintext if libssl isn't available. The Makefile also has a "compatability" build profile now without any crypto and that uses older libc networking calls.
