### ISSUE TITLE
gcc can't compile revsh

### ISSUE THREAD

**Issue by ghost** [emptymonkey/revsh#24]
OS: Kali Linux x86_64

I tried compiling with make and it gave me an error:

/usr/bin/cc -Wall -Wextra -std=c99 -pedantic -Os -DOPENSSL -o in_the_key_of_c in_the_key_of_c.c /usr/lib/x86_64-linux-gnu/libssl.a /usr/lib/x86_64-linux-gnu/libcrypto.a -ldl
/usr/lib/x86_64-linux-gnu/libcrypto.a(threads_pthread.o): In function `CRYPTO_THREAD_lock_new':
(.text+0x25): undefined reference to `pthread_rwlock_init'
/usr/lib/x86_64-linux-gnu/libcrypto.a(threads_pthread.o): In function `CRYPTO_THREAD_read_lock':
(.text+0x55): undefined reference to `pthread_rwlock_rdlock'
/usr/lib/x86_64-linux-gnu/libcrypto.a(threads_pthread.o): In function `CRYPTO_THREAD_write_lock':
(.text+0x75): undefined reference to `pthread_rwlock_wrlock'
/usr/lib/x86_64-linux-gnu/libcrypto.a(threads_pthread.o): In function `CRYPTO_THREAD_unlock':
(.text+0x95): undefined reference to `pthread_rwlock_unlock'
/usr/lib/x86_64-linux-gnu/libcrypto.a(threads_pthread.o): In function `CRYPTO_THREAD_lock_free':
(.text+0xba): undefined reference to `pthread_rwlock_destroy'
/usr/lib/x86_64-linux-gnu/libcrypto.a(threads_pthread.o): In function `CRYPTO_THREAD_run_once':
(.text+0xe5): undefined reference to `pthread_once'
/usr/lib/x86_64-linux-gnu/libcrypto.a(threads_pthread.o): In function `CRYPTO_THREAD_init_local':
(.text+0x105): undefined reference to `pthread_key_create'
/usr/lib/x86_64-linux-gnu/libcrypto.a(threads_pthread.o): In function `CRYPTO_THREAD_set_local':
(.text+0x137): undefined reference to `pthread_setspecific'
/usr/lib/x86_64-linux-gnu/libcrypto.a(threads_pthread.o): In function `CRYPTO_THREAD_cleanup_local':
(.text+0x157): undefined reference to `pthread_key_delete'
/usr/lib/x86_64-linux-gnu/libcrypto.a(threads_pthread.o): In function `CRYPTO_THREAD_get_local':
(.text+0x123): undefined reference to `pthread_getspecific'
collect2: error: ld returned 1 exit status
Makefile:138: recipe for target 'in_the_key_of_c' failed
make: *** [in_the_key_of_c] Error 1

Thanks for your help!

**Comment by ahmedm** [comment]
I think in OpenSSL 1.1.x some functions used in "in_the_key_of_c" now have a dependency on pthread library so linking with a shared OpenSSL library will pull in the dependency with no problem, but using a static library will fail, it has something to do with glibc too cause I'm building with musl libc statically without a problem

**Comment by kernel-sanders** [comment]
Adding `-pthread -ldl` to `LIBS=` allows it to compile `in_the_key_of_c` but it segfaults when run. Removing `-static` allows it to compile successfully but it is dynamically linked.

**Comment by kernel-sanders** [comment]
I think I found the issue with gcc. You have to make sure that when you configure openssl, you add the `-static` flag.

The config line for openssl should be `./config no-shared -static`.

After doing this, a full static revsh (devel branch) compiled fine with gcc.

**Comment by ahmedm** [comment]
That seems to be the problem
I'm appending the -static flag to CC and LD environment variables that's why I didn't get this issue while compiling with musl libc

    CC="/usr/local/bin/x86_64-linux-musl-gcc -static" LD="/usr/local/bin/x86_64-linux-musl-ld -static" ./Configure no-shared no-async no-hw no-comp no-zlib no-dso no-threads -fPIC linux-x86_64

**Comment by emptymonkey** [comment]
This is fixed in the current master branch. Instructions for building now include the "-static" flag when building the openssl lib.
