### ISSUE TITLE
config.h doesn't seem to support port numbers with 5 characters

### ISSUE THREAD

**Issue by GrahamMThomas** [emptymonkey/revsh#7]
Here is my config.h
<img width="274" alt="screen shot 2017-04-25 at 3 08 21 pm" src="https://cloud.githubusercontent.com/assets/14031456/25410092/b6c71ed2-29c9-11e7-9b9a-ef16e0932a1a.png">
However, when I try to launch the controller using the defaults, it appears to drop the last number.
<img width="379" alt="screen shot 2017-04-25 at 3 11 22 pm" src="https://cloud.githubusercontent.com/assets/14031456/25410089/b6c41570-29c9-11e7-9347-37ef999de917.png">
A quick double check with nmap confirms that it's not just a printing issue but also a functionality issue.
<img width="564" alt="screen shot 2017-04-25 at 3 11 39 pm" src="https://cloud.githubusercontent.com/assets/14031456/25410091/b6c53c52-29c9-11e7-810d-63ba899f28a5.png">
Throwing away the defaults, I specify the arguments manually
<img width="470" alt="screen shot 2017-04-25 at 3 12 00 pm" src="https://cloud.githubusercontent.com/assets/14031456/25410090/b6c3fb44-29c9-11e7-8393-f936b00ea992.png">
Then the port appears open.
<img width="531" alt="screen shot 2017-04-25 at 3 12 27 pm" src="https://cloud.githubusercontent.com/assets/14031456/25410093/b6cb48ea-29c9-11e7-97b3-a36dc355bbd5.png">

Assuming it's a parsing issue.

**Comment by emptymonkey** [comment]
Fixed in devel branch. ("git checkout devel"). Will leave this issue open until I push to master. (I'm going to address some of these other open issues then do more testing before push to master.)
