### ISSUE TITLE
Compatibility Mode breaks `make install`

### ISSUE THREAD

**Issue by GrahamMThomas** [emptymonkey/revsh#8]
In compatibility mode, the KEYS_DIR variable is set to ""
<img width="352" alt="screen shot 2017-04-25 at 3 29 26 pm" src="https://cloud.githubusercontent.com/assets/14031456/25410527/2772c4e0-29cc-11e7-8266-44b220332746.png">
Therefore, when the make install is run...
```
if [ ! -e $(HOME)/.revsh ]; then \
                mkdir $(HOME)/.revsh ; \ #REFERENCE 1
        fi
        if [ -e $(HOME)/.revsh/$(KEYS_DIR) ]; then \ #REFERENCE 2
                echo "\nERROR: $(HOME)/.revsh/$(KEYS_DIR) already exists! Move it safely out of the way then try again, please." ; \ 
        else \
```
Example:

It will create the `/root/.revsh` directory at REFERENCE 1

Then it will complain about the `/root/.revsh` directory at REFERENCE 2 because the KEYS_DIR variable is empty.

This can become very frustrating for the user as they try to `rm -rf` the directory and it magically reappears. 😈

**Comment by emptymonkey** [comment]
Fixed in devel. ("git checkout devel")  Will push to master after closing other issues and more testing. issue will remain open until pushed to master.
